title: Goldman Sachs Virtual Experience
description: >- # this means to ignore newlines until "baseurl:"
  Documentation of Cracking the Leaked Passwords task
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  devhiteshk

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
