title: Goldman Sachs Virtual Experience

description:
  Documentation of Cracking the Leaked Passwords task
  
github_username:  devhiteshk

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
